// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This flow analyzes code and suggests improvements to existing docstrings and identifies missing docstrings.
 *
 * - suggestImprovementsAndMissingDocstrings - A function that takes code as input and returns suggestions for docstring improvements and identifies missing docstrings.
 * - SuggestImprovementsAndMissingDocstringsInput - The input type for the suggestImprovementsAndMissingDocstrings function.
 * - SuggestImprovementsAndMissingDocstringsOutput - The return type for the suggestImprovementsAndMissingDocstrings function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestImprovementsAndMissingDocstringsInputSchema = z.object({
  code: z.string().describe('The code to analyze.'),
  language: z.string().describe('The programming language of the code (e.g., "python", "javascript").'),
});
export type SuggestImprovementsAndMissingDocstringsInput = z.infer<typeof SuggestImprovementsAndMissingDocstringsInputSchema>;

const SuggestImprovementsAndMissingDocstringsOutputSchema = z.object({
  suggestions: z.array(z.string()).describe('An array of suggestions for improving existing docstrings and identifying missing docstrings.'),
});
export type SuggestImprovementsAndMissingDocstringsOutput = z.infer<typeof SuggestImprovementsAndMissingDocstringsOutputSchema>;

export async function suggestImprovementsAndMissingDocstrings(input: SuggestImprovementsAndMissingDocstringsInput): Promise<SuggestImprovementsAndMissingDocstringsOutput> {
  return suggestImprovementsAndMissingDocstringsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestImprovementsAndMissingDocstringsPrompt',
  input: {schema: SuggestImprovementsAndMissingDocstringsInputSchema},
  output: {schema: SuggestImprovementsAndMissingDocstringsOutputSchema},
  prompt: `You are an AI documentation assistant that analyzes code and suggests improvements to existing docstrings and identifies missing docstrings.

  Analyze the following {{language}} code and provide a list of suggestions for improving existing docstrings and identifying missing docstrings. Be specific and provide actionable advice.
  Return the suggestions as a JSON object with a 'suggestions' field containing an array of strings.

  Code:
  {{{code}}}`,
});

const suggestImprovementsAndMissingDocstringsFlow = ai.defineFlow(
  {
    name: 'suggestImprovementsAndMissingDocstringsFlow',
    inputSchema: SuggestImprovementsAndMissingDocstringsInputSchema,
    outputSchema: SuggestImprovementsAndMissingDocstringsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
